version: 2

updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      npm-development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      npm-production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"

  - package-ecosystem: github-actions
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      docker-dependencies:
        patterns:
          - "*"
